//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoymaxTestBotResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoymaxTestBotResources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LoymaxTestBotResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как При выполнении команды возникла ошибка.
        /// </summary>
        internal static string ActionExecuteUnknownError {
            get {
                return ResourceManager.GetString("ActionExecuteUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Данный контакт не зарегистрирован.
        /// </summary>
        internal static string DeleteActionExecuteErrorNoContact {
            get {
                return ResourceManager.GetString("DeleteActionExecuteErrorNoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Контакт удалён из базы.
        /// </summary>
        internal static string DeleteActionExecuteOk {
            get {
                return ResourceManager.GetString("DeleteActionExecuteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Данный контакт не зарегистрирован.
        /// </summary>
        internal static string GetInfoActionExecuteErrorNoContact {
            get {
                return ResourceManager.GetString("GetInfoActionExecuteErrorNoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Сведения о контакте: {0}, дата рождения {1}.
        /// </summary>
        internal static string GetInfoActionExecuteOk {
            get {
                return ResourceManager.GetString("GetInfoActionExecuteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pong.
        /// </summary>
        internal static string PingActionExecuteOk {
            get {
                return ResourceManager.GetString("PingActionExecuteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите дату рождения.
        /// </summary>
        internal static string RegisterActionExecuteBirthDateQuestion {
            get {
                return ResourceManager.GetString("RegisterActionExecuteBirthDateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Данный контакт уже зарегистрирован.
        /// </summary>
        internal static string RegisterActionExecuteErrorContactExists {
            get {
                return ResourceManager.GetString("RegisterActionExecuteErrorContactExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Дата задана неверно, повторите ввод.
        /// </summary>
        internal static string RegisterActionExecuteErrorWrongDateFormat {
            get {
                return ResourceManager.GetString("RegisterActionExecuteErrorWrongDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите фамилию.
        /// </summary>
        internal static string RegisterActionExecuteLastNameQuestion {
            get {
                return ResourceManager.GetString("RegisterActionExecuteLastNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите отчество.
        /// </summary>
        internal static string RegisterActionExecuteMidNameQuestion {
            get {
                return ResourceManager.GetString("RegisterActionExecuteMidNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите имя.
        /// </summary>
        internal static string RegisterActionExecuteNameQuestion {
            get {
                return ResourceManager.GetString("RegisterActionExecuteNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Регистрация прошла успешно.
        /// </summary>
        internal static string RegisterActionExecuteOk {
            get {
                return ResourceManager.GetString("RegisterActionExecuteOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как не указана.
        /// </summary>
        internal static string RegisterActionExecuteOkNoBirthdaySubstring {
            get {
                return ResourceManager.GetString("RegisterActionExecuteOkNoBirthdaySubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как ФИО не указаны.
        /// </summary>
        internal static string RegisterActionExecuteOkNoFullNameSubstring {
            get {
                return ResourceManager.GetString("RegisterActionExecuteOkNoFullNameSubstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Введите личные данные для регистрации.
        /// </summary>
        internal static string RegisterActionExecuteTitle {
            get {
                return ResourceManager.GetString("RegisterActionExecuteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Регистрация не удалась: {0}.
        /// </summary>
        internal static string RegisterActionExecuteValidationFail {
            get {
                return ResourceManager.GetString("RegisterActionExecuteValidationFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Неизвестная команда.
        /// </summary>
        internal static string UnknownActionExecure {
            get {
                return ResourceManager.GetString("UnknownActionExecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Не задана фамилия.
        /// </summary>
        internal static string UserDataValidationLastNameRequired {
            get {
                return ResourceManager.GetString("UserDataValidationLastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Не задано имя.
        /// </summary>
        internal static string UserDataValidationNameRequired {
            get {
                return ResourceManager.GetString("UserDataValidationNameRequired", resourceCulture);
            }
        }
    }
}
